spring:
  security:
    saml2:
      relyingparty:
        registration:
          metadata:
            entity-id: "{baseUrl}/saml2/metadata"
            acs.location: "{baseUrl}/login/saml2/sso"
            signing.credentials:
              - private-key-location: classpath:credentials/rp-private.key
                certificate-location: classpath:credentials/rp-certificate.crt
            identityprovider:
              metadata-uri: https://simplesamlphp.apps.pcfone.io/saml2/idp/metadata.php

logging:
  level:
    org:
      springframework:
        security: TRACE
